# Generated by Django 3.2 on 2021-06-09 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_post_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_views',
        ),
    ]
