# Generated by Django 3.2 on 2021-05-24 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='linkedin_link',
            field=models.URLField(default='url'),
            preserve_default=False,
        ),
    ]
