# Generated by Django 3.2 on 2021-06-08 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_newsletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=10000)),
            ],
        ),
    ]
