# Generated by Django 3.2 on 2021-05-17 16:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_property_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
