# Generated by Django 3.2 on 2021-05-20 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_auto_20210520_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyimages',
            name='image',
            field=models.ImageField(upload_to='property_images/'),
        ),
    ]
