# Generated by Django 3.2 on 2021-05-21 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_alter_propertyimages_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyimages',
            name='image',
            field=models.ImageField(upload_to='property_images/'),
        ),
    ]
