# Generated by Django 3.2 on 2021-05-25 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_auto_20210523_0648'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
