# Generated by Django 3.2 on 2021-05-29 18:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_propertyroomfacilities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyroomfacilities',
            name='service_hours_date_from',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='propertyroomfacilities',
            name='service_hours_date_to',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
