# Generated by Django 3.2 on 2021-05-31 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_auto_20210529_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyreview',
            name='rate',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
    ]
