# Generated by Django 3.2 on 2021-05-31 04:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0016_alter_propertyreview_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyreview',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='review_author', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='propertyreview',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_property', to='property.property'),
        ),
    ]
