# Generated by Django 3.2 on 2021-05-31 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0017_auto_20210531_0427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyreview',
            name='property',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='review_property', to='property.property'),
            preserve_default=False,
        ),
    ]
