# Generated by Django 3.2 on 2021-06-16 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0018_alter_propertyreview_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyreview',
            name='rate',
            field=models.IntegerField(choices=[(1, 'Very Bad'), (2, 'Poor'), (3, 'OK'), (4, 'Good'), (5, 'Excellent')]),
        ),
    ]
