# Generated by Django 3.2 on 2021-06-16 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0019_alter_propertyreview_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyreview',
            name='rate',
            field=models.IntegerField(choices=[(1, '1 - Very Bad'), (2, '2 - Poor'), (3, '3 - OK'), (4, '4 - Good'), (5, '5 - Excellent')]),
        ),
    ]
