# Generated by Django 3.2 on 2021-06-17 13:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0021_auto_20210616_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyreview',
            name='rating',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
