# Generated by Django 3.2 on 2021-06-21 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0023_auto_20210621_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='category_ar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_category', to='property.category'),
        ),
        migrations.AddField(
            model_name='property',
            name='category_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_category', to='property.category'),
        ),
        migrations.AddField(
            model_name='property',
            name='description_ar',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='description_en',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='image_ar',
            field=models.ImageField(null=True, upload_to='property/'),
        ),
        migrations.AddField(
            model_name='property',
            name='image_en',
            field=models.ImageField(null=True, upload_to='property/'),
        ),
        migrations.AddField(
            model_name='property',
            name='name_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='owner_ar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='property',
            name='owner_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='property',
            name='place_ar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_place', to='property.place'),
        ),
        migrations.AddField(
            model_name='property',
            name='place_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_place', to='property.place'),
        ),
        migrations.AddField(
            model_name='property',
            name='price_ar',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='price_en',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
