# Generated by Django 3.2 on 2021-06-21 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0024_auto_20210621_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='category_ar',
        ),
        migrations.RemoveField(
            model_name='property',
            name='category_en',
        ),
        migrations.RemoveField(
            model_name='property',
            name='image_ar',
        ),
        migrations.RemoveField(
            model_name='property',
            name='image_en',
        ),
        migrations.RemoveField(
            model_name='property',
            name='owner_ar',
        ),
        migrations.RemoveField(
            model_name='property',
            name='owner_en',
        ),
        migrations.RemoveField(
            model_name='property',
            name='place_ar',
        ),
        migrations.RemoveField(
            model_name='property',
            name='place_en',
        ),
        migrations.RemoveField(
            model_name='property',
            name='price_ar',
        ),
        migrations.RemoveField(
            model_name='property',
            name='price_en',
        ),
    ]
